from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware 
from fastapi.responses import HTMLResponse 
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from models import SignupModel, LoginModel, ShipmentModel
from pymongo import MongoClient 
from database import users_collection
from auth import hash_password, verify_password
import time
from typing import List




app = FastAPI()

# 1. Initialize Jinja2Templates
# Assuming your 'index.html' is inside a sub-directory named 'templates/'
templates = Jinja2Templates(directory="templates") 

# 2. Configure Static Files (Recommended for serving index.css and index.js)
# Assuming your CSS and JS files are inside a sub-directory named 'static/'
# If your files are in the root directory, you can adjust the path here or move them.
# app.mount("/static", StaticFiles(directory="static"), name="static")
app.mount("/static", StaticFiles(directory="static"), name="static")

# ------------------ HELPER FOR SCM DATABASE ACCESS ------------------
def get_scm_data_collection(collection_name: str):
    """Connects to the SCM database and returns a specific collection."""
    client = MongoClient("mongodb://localhost:27017/")
    db = client["scmlitedb"]
    return db[collection_name]
# --------------------------------------------------------------------


# ------------------ CORS CONFIGURATION ------------------
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
# --------------------------------------------------------

# ------------------ ROOT ROUTE ------------------
@app.get("/", response_class=HTMLResponse)
def index(request: Request):
    return templates.TemplateResponse("index.html", {"request": request})

# --------------------------------------------------------
#Device Data Stream 
@app.get("/device-data-stream", response_class=HTMLResponse)
def device_data_stream(request: Request):
    return templates.TemplateResponse("device-data-stream.html", {"request": request})


#Dashboard
@app.get("/dashboard", response_class=HTMLResponse)
def dashboard(request: Request):
    return templates.TemplateResponse("dashboard.html", {"request": request})

#Create Shipment
@app.get("/create-shipment", response_class=HTMLResponse)
def create_shipment(request: Request):
    return templates.TemplateResponse("create-shipment.html", {"request": request})

#My Account
@app.get("/myaccount", response_class=HTMLResponse)
def my_account(request: Request):
    return templates.TemplateResponse("myaccount.html", {"request": request})

#login
@app.get("/login", response_class=HTMLResponse)
def login(request: Request):
    return templates.TemplateResponse("login.html", {"request": request})

# Signup (NEW ROUTE ADDED)
@app.get("/signup", response_class=HTMLResponse)
def signup(request: Request):
    return templates.TemplateResponse("signup.html", {"request": request})
# ------------------ 1. GET DEVICE ID LIST ------------------
# @app.get("/devices/all")
# def get_all_device_ids() -> List[str]:
#     """Returns a hardcoded list of device IDs for dropdown population."""
#     # This list corresponds to the IDs generated by server.py (1150 to 1158)
#     device_ids = [f'{1150 + i}' for i in range(9)]
#     return device_ids
# -----------------------------------------------------------


# ------------------ 2. CREATE NEW SHIPMENT ------------------
@app.post("/shipment/new")
def create_new_shipment(shipment: ShipmentModel):
    """Saves a new user-created shipment to the shipments collection."""
    try:
        collection = get_scm_data_collection("shipments_collection")
        
        # Add a unique ID and timestamp before inserting
        shipment_data = shipment.dict()
        shipment_data['timestamp'] = int(time.time())
        
        insert_result = collection.insert_one(shipment_data)
        
        return {
            "message": "Shipment created successfully",
            "shipment_id": str(insert_result.inserted_id)
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Database error during shipment creation: {e}")
# -----------------------------------------------------------


# ------------------ 3. GET ACCOUNT DETAILS ------------------
@app.get("/account/me/{email}")
def get_user_details(email: str):
    """Fetches user details using their email from the auth database."""
    db_user = users_collection.find_one({"email": email}, {"password": 0}) # Exclude password
    
    if not db_user:
        raise HTTPException(status_code=404, detail="User not found")
    
    # Convert MongoDB ObjectId to string
    db_user['_id'] = str(db_user['_id'])
    
    return db_user
# ------------------------------------------------------------


# ------------------ GET LATEST SCM DATA (POLLING) ------------------
@app.get("/device-data")
def get_latest_device_data():
    """Fetches the latest 15 documents from the live device data collection."""
    try:
        collection = get_scm_data_collection("shipment_data")
        
        latest_data = list(
            collection.find()
            .sort('_id', -1)
            .limit(15)
        )
        
        for doc in latest_data:
            doc['_id'] = str(doc['_id'])
            
        return latest_data
        
    except Exception as e:
        print(f"Database error: {e}")
        raise HTTPException(status_code=500, detail="Could not retrieve device data from database")
# --------------------------------------------------------------------


# ------------------ AUTH ROUTES ------------------
@app.post("/signup")
def signup_user(user: SignupModel):
    existing_user = users_collection.find_one({"email": user.email})
    if existing_user:
        raise HTTPException(status_code=400, detail="Email already registered")
    users_collection.insert_one({
        "name": user.name,
        "email": user.email,
        "password": hash_password(user.password)
    })
    return {"message": "Signup successful!"}

@app.post("/login")
def login_user(user: LoginModel):
    db_user = users_collection.find_one({"email": user.email})
    if not db_user:
        raise HTTPException(status_code=404, detail="User not found")
    if not verify_password(user.password, db_user["password"]):
        raise HTTPException(status_code=401, detail="Incorrect password")
    
    # Pass name and email for frontend storage
    return {
        "message": "Login successful!", 
        "user_data": {
            "name": db_user["name"], 
            "email": db_user["email"]
        }
    }